### ISSUE TITLE
Can't install dependencies on Windows 10 x64

### ISSUE THREAD

**Issue by lookapanda** [withspectrum/spectrum#2747]
```
F:\Proggen\spectrum>node shared\install-dependencies.js
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

Am I doing something wrong? :P Or is there just no compatibility with Windows? I know you guys are using Mac for working on Spectrum, so?

Just to make sure: My yarn version is 1.3.2

**Comment by lookapanda** [comment]
Just to make sure: My yarn version is 1.3.2

**Comment by lookapanda** [comment]
Okay. Just looked over the code quickly, apparently this line needs to be changed:
https://github.com/withspectrum/spectrum/blob/alpha/shared/install-dependencies.js#L27

There should be some OS check (it would need to be `yarn.cmd` for Windows)

**Comment by mxstbr** [comment]
Yeah I did 0 cross-OS checks in that file, sorry! It'd be great if you could make it work on Windows and submit a PR :pray:

**Comment by lookapanda** [comment]
https://github.com/withspectrum/spectrum/pull/2751

Done! 👌
PS: nice label added :P
