### ISSUE TITLE
"testing" database does not get created

### ISSUE THREAD

**Issue by cangoektas** [withspectrum/spectrum#2810]
**Issue Type**
- [x] Bug Report

**Description**
Currently, it's not possible to run the Cypress tests without manually creating the testing database through `NODE_ENV=test yarn run db:migrate`. I tried to address this with #2773, but maybe it's not the right solution.

According to the [integration testing](https://github.com/withspectrum/spectrum/blob/alpha/docs/testing/integration.md) document, one should run the command:

```sh
TEST_DB=true yarn run dev:api
```

However, the command fails with the following stacktrace:

```sh
➜  spectrum (alpha) ✗ TEST_DB=true yarn run dev:api
yarn run v1.5.1
$ cross-env NODE_PATH=./ cross-env NODE_ENV=development cross-env DEBUG=build*,api*,shared:middlewares*,-api:resolvers cross-env DIR=api backpack
  build:backpack > Building api, entry: api/index.js, output: build-api/main.js +0ms
> Using .babelrc defined in your app root


 DONE  Compiled successfully in 2693ms                                           19:37:37

Creating a pool connected to localhost:28015
Server starting...
  api logging with debug enabled! +0ms
GraphQL server running at http://localhost:3001/api
(node:72765) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 72 error listeners added. Use emitter.setMaxListeners() to increase limit
listenToNewMessages: ReqlOpFailedError: Database `testing` does not exist in:
r.table("messages").changes({
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    includeInitial: false
    ^^^^^^^^^^^^^^^^^^^^^
}).filter(r.row("old_val").eq(null).and(r.row("new_val").eq(null).not()))("new_val")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at Connection._processResponse (/Users/cangoektas/Developer/spectrum/node_modules/rethinkdbdash/lib/connection.js:395:15)
    at Socket.<anonymous> (/Users/cangoektas/Developer/spectrum/node_modules/rethinkdbdash/lib/connection.js:201:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
From previous event:
    at Function.Term.run (/Users/cangoektas/Developer/spectrum/node_modules/rethinkdbdash/lib/term.js:142:15)
    at Function.inspectRun [as run] (/Users/cangoektas/Developer/spectrum/node_modules/rethinkdb-inspector/dist/index.js:40:21)
    at getNewMessageChangefeed (/Users/cangoektas/Developer/spectrum/build-api/webpack:/api/models/message.js:161:6)
    at _callee$ (/Users/cangoektas/Developer/spectrum/node_modules/rethinkdb-changefeed-reconnect/lib/index.js:30:20)
    at tryCatch (/Users/cangoektas/Developer/spectrum/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/cangoektas/Developer/spectrum/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/cangoektas/Developer/spectrum/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/cangoektas/Developer/spectrum/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/cangoektas/Developer/spectrum/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/Users/cangoektas/Developer/spectrum/node_modules/core-js/library/modules/_export.js:36:28)
    at /Users/cangoektas/Developer/spectrum/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at _processChangeFeed (/Users/cangoektas/Developer/spectrum/node_modules/rethinkdb-changefeed-reconnect/lib/index.js:75:17)
    at Timeout._onTimeout (/Users/cangoektas/Developer/spectrum/node_modules/rethinkdb-changefeed-reconnect/lib/index.js:108:5)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

I also got the same error with `yarn run cypress:open` and `yarn run test:e2e`. @mxstbr mentioned that the `setup.js` script should handle the database setup. I think the setup was not running because the teardown already failed: https://github.com/withspectrum/spectrum/blob/alpha/cypress/support/index.js#L21

Wasn't able to reproduce the cypress errors though – only getting this today:

```sh
CypressError: cy.exec('node -e "const teardown = require('./shared/testing/teardown.js')().then(() => process.exit())"') timed out after waiting 60000ms.
```

**Comment by brianlovin** [comment]
It seems that the solution here is to always check for the existence of the table before starting the actual `teardown` and `setup` scripts, right?

**Comment by brian-mann** [comment]
Couldn't you just use `npm scripts` to do this before `cypress:open` and before `cypress:run` ?

https://github.com/withspectrum/spectrum/blob/alpha/package.json#L243

```js
"cypress:run": "NODE_ENV=test yarn run db:migrate && cypress run",
"cypress:open": "NODE_ENV=test yarn run db:migrate && cypress open",
```

Alternatively, you could create a cypress `script.js` file, and use our module API to first do the stuff you want to prepare the database before running or opening Cypres.

Another option (although this has some caveats) is to use the `pluginsFile` in Cypress to always automatically nuke / seed the database upon open Cypress but before running tests. If this operation is expensive and you don't want to run it **before** each test since it's just prepping the initial database scaffolding, then it makes sense to do it here.

This function will get called whenever Cypress opens whether its from `cypress open` or `cypress run`. By returning a promise it will await booting until its finished.

```js
//cypress/plugins/index.js

module.exports = (on, config) => {
  return require('./the-script-to-scaffold-the-db')()
}
````

The caveat to this is that we **watch** the plugins file and if it changes, everything will automatically re-run. If your script has side effects then it's better to run this once using the module API or an NPM script prior to running Cypress.

**Comment by brianlovin** [comment]
@brian-mann - awesome ideas; cc @mxstbr it's definitely smart to make sure the migration/scaffolding is done before cypress ever opens. Ideally the `setup` and `teardown` scripts are as fast as possible since they run before every test.

@brian-mann - we do run our `teardown` and `setup` before each test because we often test mutations which change data in the `testing` db - we don't want downstream tests to have to account for these mutations.

**Comment by brian-mann** [comment]
Right that makes sense - per this issue it seemed like you needed to first run the DB migrations else they would fail during the setup / teardown. I was suggesting those places as a "hook" where you want code to run before opening Cypress - but wouldn't want it to run in Cypress.

For instance, even using the `before` hook would run multiple times whenever you're in `cypress open` mode (since you're constantly refreshing). Putting it outside of the specs ensures it runs once and only once.

It sounds like you all have it taken care of though.

**Comment by cangoektas** [comment]
@brianlovin maybe there's something I'm missing but is it possible that the cypress setup is not the only place where we need changes for this? I'm just confused because the docs say that `TEST_DB=true yarn run dev:api` is a prerequisite for the cypress tests and that already fails.

**Comment by brianlovin** [comment]
Definitely possible our docs are misaligned, I think @mxstbr has made a lot of progress in this area in the last 12 hours or so and might be able to add more color here

**Comment by mxstbr** [comment]
Yeah that's true @cangoektas—I think I know how to handle this after #2838 lands! Will tackle then.
