### ISSUE TITLE
Push notifications are failing often on athena

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2887]
From compose: https://app.compose.io/space-program/deployments/spectrum-redis/redis/databases/0/keys/bull:push%2520notifications:notification-b3105296-4cae-4efd-ac78-0e8fa525c13d-19c4dbab-6096-487d-8f16-b3549144237a-Mon%2520Apr%252009%25202018%252016:46:54%2520GMT+0000%2520(UTC)

> ["Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.\n at invariant (/home/nowuser/src/node_modules/fbjs/lib/invariant.js:38:15)\n at convertFromRawToDraftState (/home/nowuser/src/node_modules/draft-js/lib/convertFromRawToDraftState.js:209:128)\n at toState (/home/nowuser/src/webpack:/shared/draft-utils.js:56:40)\n at formatNotification (/home/nowuser/src/webpack:/athena/utils/push-notifications/notification-formatting.js:170:25)\n at sendPushNotifications (/home/nowuser/src/webpack:/athena/utils/push-notifications/index.js:30:19)\n at <anonymous>"]

cc @mxstbr this is the ~700 failed jobs on athena

**Comment by dev-drprasad** [comment]
@brianlovin  can i get more context ? do push notifications to browser failing ? what is role of `draftjs` in sending notifications ?
