### ISSUE TITLE
cannot run data migrations windows 10

### ISSUE THREAD

**Issue by francishero** [withspectrum/spectrum#2892]
Windows 10 yarn run db:migrate fails with this error 
$ yarn run db:migrate
yarn run v1.2.1
$ npm run rethinkdb:migrate -- up

> Spectrum@2.1.6 rethinkdb:migrate C:\Users\Francis\Documents\REACT-JS-SUMMER-17\spectrum
> rethinkdb-migrate -f ./api/migrations/config.js "up"

Connecting to RethinkDB
Executing Migrations
Error while running migrations: { Error: Cannot find module 'is-html'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Francis\Documents\REACT-JS-SUMMER-17\spectrum\api\migrations\20170928143435-slate-to-draftjs.js.js:4:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at migrations.map.migration (C:\Users\Francis\AppData\Roaming\npm\node_modules\rethinkdb-migrate\lib\migrate.js:276:75)
    at Array.map (<anonymous>)
    at loadMigrationsCode (C:\Users\Francis\AppData\Roaming\npm\node_modules\rethinkdb-migrate\lib\migrate.js:276:21)
    at getMigrationsFromPath.then.then.then.migrations (C:\Users\Francis\AppData\Roaming\npm\node_modules\rethinkdb-migrate\lib\migrate.js:252:25) code: 'MODULE_NOT_FOUND' }

![image](https://user-images.githubusercontent.com/16598693/38858686-dc3b1d80-41d8-11e8-8859-e1467d8241a7.png)

**Comment by mxstbr** [comment]
Did you run `yarn` before running the migrations?

**Comment by francishero** [comment]
i did these steps here:

node shared/install-dependencies.js

started rethinkdb

then the migration :

yarn run db:migrate

**Comment by mxstbr** [comment]
Hmm, can you try to `yarn add is-html`?

**Comment by francishero** [comment]
needed to update node version, thanks
