### ISSUE TITLE
Improved GraphQL error logging

### ISSUE THREAD

**Issue by a-golovanov** [withspectrum/spectrum#2962]
We are running Spectrum for the first time and seeing the same issue as #2950. While trying to understand what's going on, we found out that the GraphQL error we are getting is not very informative:
```
  api:utils:error-formatter ---GraphQL Error--- +129ms
  api:utils:error-formatter Error: Cannot return null for non-nullable field Thread.channel.
  api:utils:error-formatter     at completeValue (.../spectrum/node_modules/graphql/execution/execute.js:596:13)
  api:utils:error-formatter     at .../spectrum/node_modules/graphql/execution/execute.js:582:14
  api:utils:error-formatter     at <anonymous>
  api:utils:error-formatter ------------------- +0ms
```
Here is how the same error message looks after we extended error logging locally:
```
  api:utils:error-formatter ---GraphQL Error--- +129ms
  api:utils:error-formatter Error: Cannot return null for non-nullable field Thread.channel.
  api:utils:error-formatter     at completeValue (.../spectrum/node_modules/graphql/execution/execute.js:596:13)
  api:utils:error-formatter     at .../spectrum/node_modules/graphql/execution/execute.js:582:14
  api:utils:error-formatter     at <anonymous> +0ms
  api:utils:error-formatter ---GraphQL Query--- +0ms
  api:utils:error-formatter query getCommunityThreadConnection($id: ID, $after: String)  +0ms
  api:utils:error-formatter { id: '1', after: null } +0ms
  api:utils:error-formatter -------------------
```
Let me know if there is any interest in this and I will submit a PR.

**Comment by brianlovin** [comment]
This would be so helpful! Any extra info about the query, variables, context, etc would all help debug <3
