### ISSUE TITLE
Searching user locally doesn't work

### ISSUE THREAD

**Issue by antsmartian** [withspectrum/spectrum#4036]
Hello, 

Thanks for such a nice product. I was trying to play around with stuff locally. I have started my servers. 

I created two users ("test1", "test2") but when I login as `test1` and search for `test2` in `/messages` url, I get the following error:

```
  shared:middlewares:logging requesting /api +181ms
err { AlgoliaSearchNetworkError: getaddrinfo ENOTFOUND undefined-dsn.algolia.net undefined-dsn.algolia.net:443
    at ClientRequest.error (/Users/abelginrayen/programs/js/spectrum/node_modules/algoliasearch/src/server/builds/node.js:229:14)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'AlgoliaSearchNetworkError',
  message:
   'getaddrinfo ENOTFOUND undefined-dsn.algolia.net undefined-dsn.algolia.net:443',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined-dsn.algolia.net',
  host: 'undefined-dsn.algolia.net',
  port: 443,
  debugData:
   [ { currentHost: 'https://undefined-1.algolianet.com',
       headers: [Object],
       content: '{"params":"query=ants&hitsPerPage=20"}',
       contentLength: 38,
       method: 'POST',
       timeouts: [Object],
       url: '/1/indexes/dev_users/query',
       startTime: 2018-10-08T06:43:53.058Z,
       endTime: 2018-10-08T06:43:53.060Z,
       duration: 2 },
     { currentHost: 'https://undefined-3.algolianet.com',
       headers: [Object],
       content: '{"params":"query=ants&hitsPerPage=20"}',
       contentLength: 38,
       method: 'POST',
       timeouts: [Object],
       url: '/1/indexes/dev_users/query',
       startTime: 2018-10-08T06:43:53.060Z,
       endTime: 2018-10-08T06:43:53.062Z,
       duration: 2 },
     { currentHost: 'https://undefined-2.algolianet.com',
       headers: [Object],
       content: '{"params":"query=ants&hitsPerPage=20"}',
       contentLength: 38,
       method: 'POST',
       timeouts: [Object],
       url: '/1/indexes/dev_users/query',
       startTime: 2018-10-08T06:43:53.062Z,
       endTime: 2018-10-08T06:43:53.065Z,
       duration: 3 },
     { currentHost: 'https://undefined-dsn.algolia.net',
       headers: [Object],
       content: '{"params":"query=ants&hitsPerPage=20"}',
       contentLength: 38,
       method: 'POST',
       timeouts: [Object],
       url: '/1/indexes/dev_users/query',
       startTime: 2018-10-08T06:43:53.065Z,
       endTime: 2018-10-08T06:43:53.068Z,
       duration: 3 } ] }
```

Kindly note I'm running athena using the command:

```
 yarn run dev:athena
```

Am I missing anything wrong?

**Comment by brianlovin** [comment]
Unfortunately we don't have local search working properly as we have to protect our Algolia credentials and can't query against our prod instance. Unfortunately the only way to work around this at the moment would be to create your own Algolia account and add the api keys to your now-secrets.json file :)

**Comment by antsmartian** [comment]
Guess that needs to be documented somewhere. May be I will open up a PR :)

**Comment by brianlovin** [comment]
Would super appreciate it if you're able to in the `README.md` at the project root :D
