### ISSUE TITLE
ReqlDriverError: None of the pools have an opened connection and failed to open a new one.

### ISSUE THREAD

**Issue by citisolo** [withspectrum/spectrum#4530]
OS: Ubuntu 18.04.1
Rethinkdb: rebirthdb 2.3.2-windows-beta-580-g54a765 (GCC 7.3.0)
Redis server v=999.999.999

I recently cloned the repo as instructed in the README but after trying to seed the database via `yarn run db:seed` I get the following error;

> { ReqlDriverError: None of the pools have an opened connection and failed to open a new one.
    at PoolMaster._flushErrors (/home/redbandit/src/spectrum/api/node_modules/rethinkhaberdashery/lib/pool_master.js:104:31)
    at Pool.<anonymous> (/home/redbandit/src/spectrum/api/node_modules/rethinkhaberdashery/lib/pool_master.js:450:12)
    at Pool.emit (events.js:182:13)
    at Pool._decreaseNumConnections (/home/redbandit/src/spectrum/api/node_modules/rethinkhaberdashery/lib/pool.js:118:10)
    at /home/redbandit/src/spectrum/api/node_modules/rethinkhaberdashery/lib/pool.js:289:10
    at tryCatcher (/home/redbandit/src/spectrum/api/node_modules/bluebird/js/release/util.js:16:23)
    at /home/redbandit/src/spectrum/api/node_modules/bluebird/js/release/catch_filter.js:24:41
    at tryCatcher (/home/redbandit/src/spectrum/api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/redbandit/src/spectrum/api/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/redbandit/src/spectrum/api/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/redbandit/src/spectrum/api/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/redbandit/src/spectrum/api/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/redbandit/src/spectrum/api/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/redbandit/src/spectrum/api/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/redbandit/src/spectrum/api/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/redbandit/src/spectrum/api/node_modules/bluebird/js/release/async.js:17:14)
  msg:
   'None of the pools have an opened connection and failed to open a new one',
  message:
   'None of the pools have an opened connection and failed to open a new one.',
  isOperational: true }
Exiting slow growth mode

**Comment by mxstbr** [comment]
You have to run rethinkdb while running `yarn run db:seed`!

**Comment by citisolo** [comment]
I am running it another tab

**Comment by mxstbr** [comment]
The seeding process cannot connect to your local database, so it might've crashed or something!

**Comment by citisolo** [comment]
I tried it again, the database is running fine,  I did investigate this a bit and found another person had this same [problem](https://github.com/rosskukulinski/kubernetes-rethinkdb-cluster/issues/35) but they're using the rethinkdbhash module directly
