### ISSUE TITLE
Deploying in ubuntu prod occurs an error

### ISSUE THREAD

**Issue by leinue** [withspectrum/spectrum#4646]
## Command

```shell
sudo yarn start:api
```

## Error

```shell
yarn run v1.13.0
$ cross-env NODE_ENV=production node build-api/main.js

/mnt/spectrum/node_modules/raven/lib/utils.js:205
    throw new Error('Invalid Sentry DSN: ' + dsn);
          ^
Error: Invalid Sentry DSN: undefined
    at Object.parseDSN (/mnt/spectrum/node_modules/raven/lib/utils.js:205:11)
    at Raven.config (/mnt/spectrum/node_modules/raven/lib/client.js:52:22)
    at Object.<anonymous> (/mnt/spectrum/build-api/webpack:/shared/raven/index.js:11:9)
    at __webpack_require__ (/mnt/spectrum/build-api/webpack:/webpack/bootstrap eee2c603af93c3430578:19:1)
    at Object.<anonymous> (/mnt/spectrum/build-api/webpack:/api/index.js:11:1)
    at __webpack_require__ (/mnt/spectrum/build-api/webpack:/webpack/bootstrap eee2c603af93c3430578:19:1)
    at Object.<anonymous> (/mnt/spectrum/build-api/main.js:6163:18)
    at __webpack_require__ (/mnt/spectrum/build-api/webpack:/webpack/bootstrap eee2c603af93c3430578:19:1)
    at module.exports.Object.defineProperty.value (/mnt/spectrum/build-api/webpack:/webpack/bootstrap eee2c603af93c3430578:62:1)
    at Object.<anonymous> (/mnt/spectrum/build-api/main.js:68:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Command

``` shell
sudo yarn start
```

## Error

```shell
yarn run v1.13.0
$ cross-env NODE_ENV=production node build-hyperion/main.js
No DATADOG_API_KEY provided, not tracking metrics.

/mnt/spectrum/build-hyperion/webpack:/shared/db/db.js:28
  throw new Error(
        ^
Error: Please provide the SSL certificate to connect to the production database in a file called `cacert` in the root directory.
    at Object.<anonymous> (/mnt/spectrum/build-hyperion/webpack:/shared/db/db.js:28:9)
    at __webpack_require__ (/mnt/spectrum/build-hyperion/webpack:/webpack/bootstrap ee65b0d920af5887ea89:25:1)
    at Object.<anonymous> (/mnt/spectrum/build-hyperion/webpack:/shared/db/index.js:2:1)
    at __webpack_require__ (/mnt/spectrum/build-hyperion/webpack:/webpack/bootstrap ee65b0d920af5887ea89:25:1)
    at Object.module.exports.Object.defineProperty.value (/mnt/spectrum/build-hyperion/webpack:/shared/db/queries/user.js:2:1)
    at __webpack_require__ (/mnt/spectrum/build-hyperion/webpack:/webpack/bootstrap ee65b0d920af5887ea89:25:1)
    at Object.<anonymous> (/mnt/spectrum/build-hyperion/webpack:/hyperion/index.js:14:1)
    at Object.<anonymous> (/mnt/spectrum/build-hyperion/main.js:25116:30)
    at __webpack_require__ (/mnt/spectrum/build-hyperion/webpack:/webpack/bootstrap ee65b0d920af5887ea89:25:1)
    at Object.<anonymous> (/mnt/spectrum/build-hyperion/main.js:24847:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by leinue** [comment]
How can i get cacert?

**Comment by leinue** [comment]
Now I have generated the `cacert`, also error:

```shell
Error: Invalid Sentry DSN: undefined
yarn run v1.13.0
$ cross-env NODE_ENV=production node build-hyperion/main.js
No DATADOG_API_KEY provided, not tracking metrics.
Creating a pool connected to localhost:28015

/mnt/spectrum/node_modules/raven/lib/utils.js:205
    throw new Error('Invalid Sentry DSN: ' + dsn);
          ^
Error: Invalid Sentry DSN: undefined
    at Object.parseDSN (/mnt/spectrum/node_modules/raven/lib/utils.js:205:11)
    at Raven.config (/mnt/spectrum/node_modules/raven/lib/client.js:52:22)
    at Object.module.exports.Object.defineProperty.value (/mnt/spectrum/build-hyperion/webpack:/shared/raven/index.js:11:9)
    at __webpack_require__ (/mnt/spectrum/build-hyperion/webpack:/webpack/bootstrap ee65b0d920af5887ea89:25:1)
    at Object.<anonymous> (/mnt/spectrum/build-hyperion/webpack:/api/utils/s3.js:6:1)
    at __webpack_require__ (/mnt/spectrum/build-hyperion/webpack:/webpack/bootstrap ee65b0d920af5887ea89:25:1)
    at getUploadImageFn (/mnt/spectrum/build-hyperion/webpack:/api/utils/file-storage.js:14:14)
    at Object.<anonymous> (/mnt/spectrum/build-hyperion/webpack:/api/utils/file-storage.js:18:23)
    at __webpack_require__ (/mnt/spectrum/build-hyperion/webpack:/webpack/bootstrap ee65b0d920af5887ea89:25:1)
    at Object.module.exports.Object.defineProperty.value (/mnt/spectrum/build-hyperion/webpack:/shared/db/queries/user.js:3:1)
    at __webpack_require__ (/mnt/spectrum/build-hyperion/webpack:/webpack/bootstrap ee65b0d920af5887ea89:25:1)
    at Object.<anonymous> (/mnt/spectrum/build-hyperion/webpack:/hyperion/index.js:14:1)
    at Object.<anonymous> (/mnt/spectrum/build-hyperion/main.js:25116:30)
    at __webpack_require__ (/mnt/spectrum/build-hyperion/webpack:/webpack/bootstrap ee65b0d920af5887ea89:25:1)
    at Object.<anonymous> (/mnt/spectrum/build-hyperion/main.js:24847:18)
    at __webpack_require__ (/mnt/spectrum/build-hyperion/webpack:/webpack/bootstrap ee65b0d920af5887ea89:25:1)
    at /mnt/spectrum/build-hyperion/webpack:/webpack/bootstrap ee65b0d920af5887ea89:90:1
    at Object.<anonymous> (/mnt/spectrum/build-hyperion/main.js:96:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.

```

**Comment by mxstbr** [comment]
The `cacert` needs to be downloaded from your database host, it is the certificate the servers use to connect to RethinkDB with SSL.

You also need to sign up for all the services and fill out all the environment variables with their secrets.
